name: Save Registration Details

on:
  workflow_dispatch:
    inputs:
      phone:
        description: 'Phone Number'
        required: true
      pin:
        description: 'PIN'
        required: true
      userType:
        description: 'User Type'
        required: true

jobs:
  save-registration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Save registration details
        run: |
          echo "phone,pin,userType" > registration.csv
          echo "${{ github.event.inputs.phone }},${{ github.event.inputs.pin }},${{ github.event.inputs.userType }}" >> registration.csv
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add registration.csv
          git commit -m "Add new registration details"
          git push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
